FROM parity/parity:v2.2.3


EXPOSE 30303

EXPOSE 8545

EXPOSE 8546

CMD ["--jsonrpc-interface", "all", \
 "--dapps-apis-all", "--jsonrpc-apis", "all", "--snapshot-peers", "16", "--warp-barrier", "7145000"]
